In [3]:
import numpy as np

In [4]:
##dizi olıuşturma
arr = np.array([1,2,3,4,5])
print("1. np.array()=", arr)

1. np.array()= [1 2 3 4 5]


In [5]:
##Belirli bir aralıkta düzenli artan sayılarla dizi oluşturma
arr_range = np.arange(0, 10, 2)
print("2. np.arange():", arr_range)

2. np.arange(): [0 2 4 6 8]


In [6]:
# Belirtilen aralıkta eşit aralıklı sayılar oluşturma
arr_linspace = np.linspace(0, 10, 5)
print("3. np.linspace():", arr_linspace)

3. np.linspace(): [ 0.   2.5  5.   7.5 10. ]


In [7]:
# Sıfırlarla dolu bir dizi oluşturma
arr_zeros = np.zeros((2, 3))
print("4. np.zeros():\n", arr_zeros)

4. np.zeros():
 [[0. 0. 0.]
 [0. 0. 0.]]


In [9]:
# Birlerle dolu bir dizi oluşturma
arr_ones = np.ones((5, 8))
print("5. np.ones():\n", arr_ones)

5. np.ones():
 [[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


In [10]:
# Birim matris oluşturma
identity_matrix = np.eye(4)
print("6. np.eye():\n", identity_matrix)

6. np.eye():
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [11]:
# 0 ile 1 arasında rastgele sayılar içeren bir dizi oluşturma
random_array = np.random.rand(3, 3)
print("7. np.random.rand():\n", random_array)

7. np.random.rand():
 [[0.33650946 0.89252194 0.97342272]
 [0.09563535 0.96725233 0.80459354]
 [0.32719256 0.18199232 0.68395197]]


In [12]:
# Dizinin ortalamasını hesaplama
arr_mean = np.mean(arr)
print("8. np.mean():", arr_mean)

8. np.mean(): 3.0


In [13]:
# Dizinin elemanlarını toplama
arr_sum = np.sum(arr)
print("9. np.sum():", arr_sum)


9. np.sum(): 15


In [14]:
# Dizinin şeklini değiştirme
reshaped_arr = np.arange(1, 10).reshape(3, 3)
print("10. np.reshape():\n", reshaped_arr)


10. np.reshape():
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
